name: Compile Iris
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the correct repository
        uses: actions/checkout@v3
        with:
          repository: VolmitSoftware/Iris
          path: iris

      - name: Show repo structure (Debugging)
        run: ls -R iris

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Gradle
        run: sudo apt update && sudo apt install gradle -y

      - name: Move into the correct directory and build
        run: |
          cd iris
          if [ -f "build.gradle" ]; then
            ./gradlew build
          else
            echo "Error: build.gradle not found!"
            exit 1
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Iris-JAR
          path: iris/build/libs/*.jar
