name: Compile Iris
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Move into the correct directory
        run: cd ${{ github.workspace }} && ls && mvn clean package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Iris-JAR
          path: iris/target/*.jar
