name: Compile Iris
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the correct repository
        uses: actions/checkout@v3
        with:
          repository: VolmitSoftware/Iris  # Correct repo
          path: iris  # Clones into a folder named 'iris'

      - name: Show repo structure (Debugging)
        run: ls -R iris  # Check where pom.xml is

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maven
        run: sudo apt update && sudo apt install maven -y

      - name: Find the actual pom.xml location
        run: find iris -name "pom.xml"

      - name: Move into the correct directory and compile
        run: |
          cd iris
          if [ -f "pom.xml" ]; then
            mvn clean package
          else
            echo "Error: pom.xml not found!"
            exit 1
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Iris-JAR
          path: iris/target/*.jar
